### ISSUE TITLE
feat: improve logging when aapt fails

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-library#6]
### Type

Functionality

### Issue

If a reference to a string resource is added by a patch, but the string was not added, then during resource compilation aapt fails with no explanation:

```
INFO: Compiling modified resources 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/fl/y1nm82nj2n96vtck6yqhndb00000gn/T/brut_util_Jar_147215652418537425292855373659709497765.tmp, link, -o, /Users/liso/Code/temp/revanced-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539440064, --version-name, 18.32.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /var/folders/fl/y1nm82nj2n96vtck6yqhndb00000gn/T/APKTOOL4133149550015619124.tmp, -0, arsc, -I, /Users/liso/Code/temp/revanced-resource-cache/1.apk, --manifest, /Users/liso/Code/temp/revanced-resource-cache/AndroidManifest.xml, /Users/liso/Code/temp/revanced-resource-cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:232)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:195)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
```

### Feature

Connect aapt to the patchers logging output.  If it spams the logs or it's not possible to show only aapt log errors, then add a new patcher option for verbose logging and let aapt print everything.

This [might be possible](https://www.github.com/ReVanced/revanced-patches/pull/2366#issuecomment-1712820511), but I am not familiar enough with aapt to try making this change myself.

### Motivation

Stop wasting so much time figuring out which resource is missing when aapt compilation fails.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The log in question that has to be enabled is this:

https://github.com/revanced/Apktool/blob/b83b58e8e8cf0b880caf5a3dafafad63c534ac4d/brut.j.util/src/main/java/brut/util/OS.java#L164
