### ISSUE TITLE
bug: FailedToFindInstalledPackageException when installing with --mount

### ISSUE THREAD

**Issue by ricnava00** [ReVanced/revanced-library#64]
### Bug description

java -jar revanced-cli-5.0.0-all.jar  patch -p patches-5.0.1.rvp -i [serial] -o output.apk --mount com.google.android.youtube_19.43.41.apk

Raises FailedToFindInstalledPackageException

### Error logs

```shell
...
INFO: Installing com.google.android.youtube by mounting
app.revanced.library.installation.installer.RootInstaller$FailedToFindInstalledPackageException: Failed to find installed package "com.google.android.youtube" because no activity was found
        at app.revanced.library.installation.installer.RootInstaller.assertInstalled(RootInstaller.kt:126)
        at app.revanced.library.installation.installer.RootInstaller.install$suspendImpl(RootInstaller.kt:55)
        at app.revanced.library.installation.installer.RootInstaller.install(RootInstaller.kt)
        at app.revanced.cli.command.PatchCommand$run$4$1.invokeSuspend(PatchCommand.kt:360)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:359)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

### Solution

Unfortunately I couldn't verify this, but it seems to me that the condition in https://github.com/ReVanced/revanced-library/blob/cace51700aa9eff16668900f150a773bdbed7a33/src/commonMain/kotlin/app/revanced/library/installation/installer/RootInstaller.kt#L125 is inverted

### Additional context

Running:
pm path com.google.android.youtube
Returns:
package:/data/app/~~_bb1lYTjLPKioHG4NpBMhQ==/com.google.android.youtube-CYzdlf-q6aJnotZmD7abCA==/base.apk

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
May be fixed with https://github.com/ReVanced/revanced-library/commit/649f06b19dd4d2a3f3216a0b3ea947b9fe0d475f. You can test by bumping the version of the library in ReVanced CLI.

**Comment by ricnava00** [comment]
Yes, the issue is fixed. Thank you.
